{
 "title": "Fraud Detection Pipeline",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Transactions / seconde",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(transactions_processed_total[1m])",
     "legendFormat": "tx/s"
    }
   ]
  },
  {
   "title": "Fraudes détectées (1h)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "increase(frauds_detected_total[1h])",
     "legendFormat": "fraudes"
    }
   ]
  },
  {
   "title": "Latence P95 (secondes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(processing_latency_seconds_bucket[5m]))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Taux de fraude %",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(frauds_detected_total[5m]) / rate(transactions_processed_total[5m]) * 100",
     "legendFormat": "fraude %"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 4, "w": 18, "h": 8 },
   "targets": [
    { "expr": "kafka_consumer_lag", "legendFormat": "topic: {{topic}}" }
   ]
  }
 ]
}